### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arr-ee**
Should be merged before releasing `0.2.0` or whatever the next version is.

### CODE REVIEW

**Comment by technomancy** [comment]
Send me your Clojars username and I'll let you handle the whole `0.2.0` release.

**Comment by arr-ee** [comment]
Name's arre.
Thanks!

**Comment by technomancy** [comment]
Great; you should have access on Clojars now.

**Comment by arr-ee** [comment]
Awesome, thanks!

**Pull request merged**
